#!/usr/bin/env python3
"""
HeyReach API tracker.

Fetches the live HeyReach public Postman collection, extracts every endpoint,
and diffs it against the last saved snapshot. On any change it:
  1. rewrites docs/heyreach-api-reference.md   (human-readable, grouped)
  2. rewrites docs/heyreach-api-snapshot.json  (machine snapshot for diffing)
  3. appends an entry to docs/heyreach-api-CHANGELOG.md

Detection is purely mechanical (no API key, no LLM) so it is safe to run on a
schedule. Exit code 0 = no change, 2 = changes detected (handy for cron/notify).

Usage:
    python3 scripts/09_heyreach_api_tracker.py            # check + apply on change
    python3 scripts/09_heyreach_api_tracker.py --check    # report only, write nothing
"""

import json
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

COLLECTION_URL = "https://documenter.gw.postman.com/api/collections/23808049/2sA2xb5F75"

DOCS = Path(__file__).resolve().parent.parent / "docs"
SNAPSHOT = DOCS / "heyreach-api-snapshot.json"
REFERENCE = DOCS / "heyreach-api-reference.md"
CHANGELOG = DOCS / "heyreach-api-CHANGELOG.md"


def fetch_collection():
    req = urllib.request.Request(COLLECTION_URL, headers={"User-Agent": "heyreach-api-tracker"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode("utf-8"))


def endpoint_path(raw):
    """Normalize a Postman raw URL down to the path after /api/public."""
    if not raw:
        return raw
    path = raw
    if "api/public" in raw:
        path = "/" + raw.split("api/public", 1)[1].lstrip("/")
    return path.split("?")[0]


def walk(items, folder, out):
    for it in items:
        if "item" in it:
            walk(it["item"], it.get("name", folder), out)
        else:
            req = it.get("request", {})
            url = req.get("url")
            raw = url.get("raw") if isinstance(url, dict) else url
            desc = req.get("description") or it.get("description") or ""
            if isinstance(desc, dict):
                desc = desc.get("content", "")
            out.append({
                "group": folder,
                "name": it.get("name", ""),
                "method": req.get("method", "?"),
                "path": endpoint_path(raw),
                "description": " ".join(str(desc).split())[:300],
            })


def extract(collection):
    out = []
    walk(collection.get("item", []), collection.get("info", {}).get("name", "root"), out)
    # stable ordering
    out.sort(key=lambda e: (e["group"], e["path"], e["method"]))
    return out


def key(e):
    return f"{e['method']} {e['path']}"


def load_prev():
    if SNAPSHOT.exists():
        return json.loads(SNAPSHOT.read_text())
    return None


def diff(prev, curr):
    prev_map = {key(e): e for e in (prev.get("endpoints", []) if prev else [])}
    curr_map = {key(e): e for e in curr}
    added = [curr_map[k] for k in curr_map if k not in prev_map]
    removed = [prev_map[k] for k in prev_map if k not in curr_map]
    changed = []
    for k in curr_map:
        if k in prev_map and curr_map[k].get("name") != prev_map[k].get("name"):
            changed.append((prev_map[k], curr_map[k]))
    added.sort(key=key)
    removed.sort(key=key)
    return added, removed, changed


def render_reference(endpoints, stamp):
    groups = {}
    for e in endpoints:
        groups.setdefault(e["group"], []).append(e)
    lines = []
    lines.append("# HeyReach Public API Reference")
    lines.append("")
    lines.append("> AUTO-GENERATED by `scripts/09_heyreach_api_tracker.py`. Do not edit by hand.")
    lines.append(f"> Last synced: {stamp}")
    lines.append(f"> Source: {COLLECTION_URL}")
    lines.append("")
    lines.append("- **Base URL:** `https://api.heyreach.io/api/public`")
    lines.append("- **Auth:** `X-API-KEY` header (keys never expire; can be deactivated)")
    lines.append("- **Rate limit:** 300 requests / minute, shared across all endpoints (429 on breach)")
    lines.append(f"- **Total endpoints:** {len(endpoints)} across {len(groups)} groups")
    lines.append("")
    lines.append("## Groups")
    lines.append("")
    for g in groups:
        lines.append(f"- [{g}](#{g.lower().replace(' ', '-')}) ({len(groups[g])})")
    lines.append("")
    for g, eps in groups.items():
        lines.append(f"## {g}")
        lines.append("")
        lines.append("| Method | Endpoint | Path |")
        lines.append("|--------|----------|------|")
        for e in eps:
            lines.append(f"| {e['method']} | {e['name']} | `{e['path']}` |")
        lines.append("")
    return "\n".join(lines) + "\n"


def append_changelog(added, removed, changed, stamp):
    entry = [f"\n## {stamp}", ""]
    if added:
        entry.append("### Added")
        for e in added:
            entry.append(f"- `{e['method']} {e['path']}` ({e['group']} / {e['name']})")
        entry.append("")
    if removed:
        entry.append("### Removed")
        for e in removed:
            entry.append(f"- `{e['method']} {e['path']}` ({e['group']} / {e['name']})")
        entry.append("")
    if changed:
        entry.append("### Renamed")
        for old, new in changed:
            entry.append(f"- `{key(new)}`: \"{old['name']}\" -> \"{new['name']}\"")
        entry.append("")
    text = "\n".join(entry)
    if not CHANGELOG.exists():
        header = "# HeyReach API Changelog\n\nTracked automatically. Newest entries appended at the bottom.\n"
        CHANGELOG.write_text(header + text)
    else:
        CHANGELOG.write_text(CHANGELOG.read_text() + text)


def main():
    check_only = "--check" in sys.argv
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    try:
        collection = fetch_collection()
    except Exception as exc:
        print(f"ERROR: could not fetch collection: {exc}", file=sys.stderr)
        return 1

    curr = extract(collection)
    prev = load_prev()
    added, removed, changed = diff(prev, curr)

    if prev is None:
        print(f"Baseline established: {len(curr)} endpoints.")
    elif not (added or removed or changed):
        print(f"No changes. {len(curr)} endpoints, in sync as of {stamp}.")
        return 0
    else:
        print(f"CHANGES DETECTED as of {stamp}:")
        for e in added:
            print(f"  + {key(e)}  ({e['group']} / {e['name']})")
        for e in removed:
            print(f"  - {key(e)}  ({e['group']} / {e['name']})")
        for old, new in changed:
            print(f"  ~ {key(new)}  renamed '{old['name']}' -> '{new['name']}'")

    if check_only:
        return 2 if (added or removed or changed) else 0

    REFERENCE.write_text(render_reference(curr, stamp))
    SNAPSHOT.write_text(json.dumps(
        {"synced": stamp, "count": len(curr), "endpoints": curr}, indent=2) + "\n")
    if prev is not None and (added or removed or changed):
        append_changelog(added, removed, changed, stamp)

    print(f"Wrote {REFERENCE.name}, {SNAPSHOT.name}"
          + (f", updated {CHANGELOG.name}" if prev is not None and (added or removed or changed) else ""))
    return 2 if (prev is not None and (added or removed or changed)) else 0


if __name__ == "__main__":
    sys.exit(main())
